version: "3"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_local
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost # Ganti dengan IP VPS saat di-deploy
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/ # Ganti dengan http://[IP-VPS]:5678/
      - GENERIC_TIMEZONE=Asia/Jakarta
    volumes:
      - ./n8n_data:/home/node/.n8n
